blank_issues_enabled: true
contact_links:
  - name: 🤔 Support/Usage Question
    url: https://community.openhab.org/c/apps-services/garmin-app/
    about: Feel free to ask anything
  - name: 📖 openHAB Garmin Scripting Documentation
    url: https://next.openhab.org/docs/apps/garmin/#settings-menu
    about: Official documentation
